### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by prawnguy** [phucynwa/Geckompose#19]
Are you still maintaining this project?
I'm interested in using it. But It looks like all your builds are failing on [JitPack](https://jitpack.io/com/github/phucynwa/Geckompose/main-140c3eaf98-1/build.log).

**Comment by phucynwa** [comment]
Thank you for being interested. I still maintain it.
I will try to publish it to maven central if possible.

**Comment by prawnguy** [comment]
That's great! I'll be sure to set it up once I continue with my project.
Thanks a lot!
